### ISSUE TITLE
what is the format of your training data ? 

### ISSUE THREAD

**Issue by Ghul-huan** [sirius-ai/LPRNet_Pytorch#1]
what is the format of your training data ?

**Comment by sirius-ai** [comment]
see [test data](https://github.com/sirius-ai/LPRNet_Pytorch/tree/master/data/test)

**Comment by Ghul-huan** [comment]
如果图片名字为标签的话，跑训练代码报了这样的问题：Expected tensor for argument #2 'targets' to have scalar type Int; but got torch.FloatTensor instead (while checking arguments for ctc_loss_cpu)
ctc_loss的输入是部哪里有问题

**Comment by sirius-ai** [comment]
@Ghul-huan 麻烦你发出你的训练数据给我看一下，训练数据应该如./data/test目录下的形式一致。

**Comment by sirius-ai** [comment]
[fix](https://github.com/sirius-ai/LPRNet_Pytorch/commit/d2a46af7609675c3a99857eaf909497bf6541bcc)
