### ISSUE TITLE
Why MaxPool3d instead of MaxPool2d?

### ISSUE THREAD

**Issue by deep-practice** [sirius-ai/LPRNet_Pytorch#10]

**Comment by sirius-ai** [comment]
Because MaxPool2d can't pooling in channel dimension.

**Comment by deep-practice** [comment]
What's the benefit of pooling in channel dimension?@sirius-ai

**Comment by sirius-ai** [comment]
its LPRNet architecture network, maybe less paramerers and cost less compute power.
