### ISSUE TITLE
Problem when custom training for 37 class

### ISSUE THREAD

**Issue by joshzhung** [sirius-ai/LPRNet_Pytorch#13]
I want training a model without chinese , so I remove that from CHARS  in load_data.py and command the check function 
CHARS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9','A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V','W', 'X', 'Y', 'Z', 'I', 'O', '-' ],

I got a error message when I training without pretrainmodle , 
RuntimeError: Given groups=1, weight of size [37,516,1,1] , expected input [128,485,4,18] to have 516 channels , but got 485 channels instead
I got a error message when I training with pretrainmodle , 
size mismatch for container.0,bias: copying a param with shape torch.Size([68]) from checkpoint, the shape in current model is torch.Size([37])

How can I custom training , please help , thanks.

**Comment by sirius-ai** [comment]
[done](https://github.com/sirius-ai/LPRNet_Pytorch/commit/330c09cc7a4bbe06773c466bcffd34c55faff5bb)
