### ISSUE TITLE
训练过程中的数据增强策略

### ISSUE THREAD

**Issue by Soulempty** [sirius-ai/LPRNet_Pytorch#15]
大佬你好，看到你说车牌裁剪方式要一致，我也有很多车牌数据，是通过标注框裁剪的，用的是keras的ctc训练，但是训练得到模型会对车牌的边缘大小或者检测框的偏移敏感，大佬有遇到这个问题吗？
还有就是训练的数据增强方法需要注意哪些？

**Comment by sirius-ai** [comment]
保障裁剪方式一致性应该就没这个问题了，数据增强尽量与真实环境保持一致就好。
