### ISSUE TITLE
数据集要怎么制作呀，或者有啥要求，麻烦大佬告知

### ISSUE THREAD

**Issue by 2017TJM** [sirius-ai/LPRNet_Pytorch#16]
数据集要怎么制作呀，或者有啥要求，麻烦大佬

**Comment by sirius-ai** [comment]
如果有条件可以直接收集现实生活中的数据，这样更有效。但是如果没这个条件，可以搜罗网络上开源的数据集如CCPD。如果自己手工制作车牌，那么就要尽可能做到逼真即可。
