### ISSUE TITLE
使用提供的模型进行再训练loss值很高，最后得到的模型acc为0

### ISSUE THREAD

**Issue by Roxbili** [sirius-ai/LPRNet_Pytorch#26]
**训练文件：train_LPRNet.py**

训练集就使用./data/test文件夹下的样例，使用lprnet.train()模式下不知道为什么loss值很高(差不多20+左右)，即使学习率特别小，最后训练出模型也什么都识别不出来，测试Accuracy为0。

同样使用提供的模型，将学习率改成0不让它学习，输出的模型也什么都识别不出来，acc为0.

更改过的代码部分如下（model文件夹下LPRNet.py文件）：
```
def build_lprnet(lpr_max_len=8, phase=False, class_num=66, dropout_rate=0.5):   # dropout_rate随机失活的比例，0.5可以大幅度改变网络结构

    Net = LPRNet(lpr_max_len, phase, class_num, dropout_rate)

    if phase == True:   # 这里phase是bool型，不是str
        return Net.train()
    else:
        return Net.eval()
```

**Comment by iamrishab** [comment]
Have you found a solution to this problem?

**Comment by Roxbili** [comment]
Not yet, I trained a new model and this problem no longer occurs.
