### ISSUE TITLE
the issue of training data format

### ISSUE THREAD

**Issue by pangyanhui923** [sirius-ai/LPRNet_Pytorch#4]
What is the label format of your training data set ? Can you provide a sample ?

**Comment by sirius-ai** [comment]
[see ./data/test direcrory.](https://github.com/sirius-ai/LPRNet_Pytorch/tree/master/data/test)

**Comment by pangyanhui923** [comment]
Don't you need a label?Directly change the name of the image to license plate content data how to load?

**Comment by sirius-ai** [comment]
label is the filename，source code can see from [load_data.py](https://github.com/sirius-ai/LPRNet_Pytorch/blob/master/data/load_data.py) and which show you how to load image and its label.

**Comment by pangyanhui923** [comment]
Thank you!
