### ISSUE TITLE
这是我自己加了一些字符后训练后测试的结果，简直是惨不忍睹呀！

### ISSUE THREAD

**Issue by rawli** [sirius-ai/LPRNet_Pytorch#48]
这是我自己加了"港", "学", "使", "警", "澳", "挂", "军", "北", "南", "广", "沈", "兰", "成", "济", "海", "民", "航", "空", "应", "急", "试", "超"这些字符后训练后测试的结果，我使用的是100多万张真实的数据训练的，结果惨不忍睹，我搞不清楚是什么原因。

Successful to build network!
load pretrained model successful!
target:  皖HB5421  ### F ###  predict:  浙B9B5B5B2B
target:  浙BU8Z98  ### F ###  predict:  浙B9505088
target:  苏BY2861  ### F ###  predict:  浙B59595B59B
target:  浙B2659W  ### F ###  predict:  浙508807
target:  浙KK4896  ### F ###  predict:  浙B5B5B5B5
target:  苏BM7292  ### F ###  predict:  浙B9B9B9B
target:  浙B8Z809  ### F ###  predict:  浙B59B5B5B59
target:  浙B21AW6  ### F ###  predict:  浙95088B9
target:  皖M16224  ### F ###  predict:  浙5958
target:  沪C3QW66  ### F ###  predict:  浙9B9B9
target:  浙A92V29  ### F ###  predict:  浙B9B9B9B9B9
target:  苏ER73P5  ### F ###  predict:  浙B9B9A9A9
target:  浙A799ZB  ### F ###  predict:  浙B90505090
target:  浙AT203Z  ### F ###  predict:  浙9
target:  苏GD160C  ### F ###  predict:  浙590087
target:  鄂KB8L75  ### F ###  predict:  80577958
target:  浙ACK665  ### F ###  predict:  浙9A9508
target:  鲁GP0687  ### F ###  predict:  浙92B929
target:  冀D7H902  ### F ###  predict:  浙9
target:  冀EH7609  ### F ###  predict:  浙9
target:  浙BM91Q6  ### F ###  predict:  浙9B9
target:  渝A3895E  ### F ###  predict:  浙9
target:  沪EH1531  ### F ###  predict:  浙92929
target:  赣EG9837  ### F ###  predict:  浙9
target:  沪EB2500  ### F ###  predict:  浙9B9B9
target:  浙B28A2F  ### F ###  predict:  浙9B90950
target:  冀FT9538  ### F ###  predict:  浙959
target:  浙B6B87E  ### F ###  predict:  浙57
target:  浙C3WE61  ### F ###  predict:  浙9
target:  浙AC1W07  ### F ###  predict:  浙B9B9B59
target:  鲁US8207  ### F ###  predict:  浙B9B9B9B9
target:  浙F8KJ01  ### F ###  predict:  浙B9B9B9
target:  浙B1D857  ### F ###  predict:  浙0506B95
target:  鲁D760TG  ### F ###  predict:  浙A9A90浙B9
target:  豫PVH205  ### F ###  predict:  浙08087
target:  苏E8LX85  ### F ###  predict:  浙B9A5A9
target:  浙B1F750  ### F ###  predict:  浙B92929B9
target:  赣EU1508  ### F ###  predict:  浙B9BA9P9PB95A95
target:  赣F79Z58  ### F ###  predict:  浙9059
target:  浙B6GN95  ### F ###  predict:  浙507507
target:  鲁R8DN03  ### F ###  predict:  浙95E9
target:  浙B1N068  ### F ###  predict:  浙9
target:  浙BF67Z8  ### F ###  predict:  浙9B9
target:  浙JM866F  ### F ###  predict:  浙95E5
target:  浙AM697M  ### F ###  predict:  浙9
target:  浙B7E281  ### F ###  predict:  浙9
target:  皖SAE023  ### F ###  predict:  浙9
target:  皖A238Y2  ### F ###  predict:  浙99
target:  浙G9B8A7  ### F ###  predict:  浙B9BA9B9
target:  苏E8K0M9  ### F ###  predict:  浙9浙9浙9浙9浙9
target:  浙A58C88  ### F ###  predict:  浙B5076
target:  浙BDE268  ### F ###  predict:  浙50885
target:  浙A7AE63  ### F ###  predict:  浙5083508
target:  鲁Q9889H  ### F ###  predict:  豫B
target:  浙HD8859  ### F ###  predict:  豫B
target:  浙AHZ402  ### F ###  predict:  浙B08850
target:  浙G9GF57  ### F ###  predict:  浙505070505
target:  皖KK9658  ### F ###  predict:  豫B
target:  浙FX527P  ### F ###  predict:  浙359088088
target:  浙B2X5A0  ### F ###  predict:  浙B905B
target:  浙B97525  ### F ###  predict:  豫B5B5B
target:  浙AE0T56  ### F ###  predict:  豫B5
target:  浙B0GC35  ### F ###  predict:  豫B
target:  浙A5B3M5  ### F ###  predict:  豫50S7苏
target:  浙AJ27D3  ### F ###  predict:  豫B5B508885
target:  浙FK5C23  ### F ###  predict:  豫B
target:  皖J66748  ### F ###  predict:  豫B5B5
target:  沪C6X5C0  ### F ###  predict:  豫B
target:  渝DR9737  ### F ###  predict:  豫5B5B5B5B5B5
target:  浙BE89M7  ### F ###  predict:  豫B5B5
target:  沪EH8851  ### F ###  predict:  京B
target:  豫PF635P  ### F ###  predict:  京B5
target:  浙AFK291  ### F ###  predict:  京B
target:  浙B0D173  ### F ###  predict:  京B5B5
target:  湘AU0M01  ### F ###  predict:  京B5B5
target:  沪C0S7Z5  ### F ###  predict:  京B508
target:  沪C967QL  ### F ###  predict:  豫B
target:  浙HS4026  ### F ###  predict:  京B5B5B5B5B
target:  豫NE089Z  ### F ###  predict:  京B5
target:  豫P75H91  ### F ###  predict:  京5650S8
target:  浙A5B5M9  ### F ###  predict:  浙9B9B9B9
target:  豫SJS166  ### F ###  predict:  浙50757708
target:  浙B95026  ### F ###  predict:  浙9B9B9B9
target:  鲁RQ0283  ### F ###  predict:  浙9B9
target:  浙F708BL  ### F ###  predict:  浙9
target:  浙AQJ088  ### F ###  predict:  浙9B9B9595浙
target:  赣E528K3  ### F ###  predict:  浙B907578
target:  浙BH287R  ### F ###  predict:  浙9539B508859
target:  浙BA8T70  ### F ###  predict:  浙B9B9浙9508苏
target:  京N5UH88  ### F ###  predict:  浙B9B9
target:  浙A1024T  ### F ###  predict:  京B
target:  浙AKR627  ### F ###  predict:  京B
target:  赣C1858J  ### F ###  predict:  京B
target:  苏GR7378  ### F ###  predict:  豫B535
target:  粤T073K5  ### F ###  predict:  京B
target:  浙AEP970  ### F ###  predict:  豫B50878
target:  浙B1U831  ### F ###  predict:  京B
target:  浙BUL998  ### F ###  predict:  京B
target:  浙B68ZU9  ### F ###  predict:  豫5B50S8850
target:  浙EE011B  ### F ###  predict:  豫B5B5B
target:  浙JG66T0  ### F ###  predict:  京B
target:  辽H24166  ### F ###  predict:  豫B5B
target:  浙A5D0E1  ### F ###  predict:  豫B
target:  浙B5896Y  ### F ###  predict:  豫B5
target:  浙AC393G  ### F ###  predict:  豫5B5775
target:  苏URZ332  ### F ###  predict:  京B5B5B5
target:  鲁K95238  ### F ###  predict:  豫B
target:  浙BT2270  ### F ###  predict:  京B
target:  苏GC3367  ### F ###  predict:  京B
target:  苏EYF919  ### F ###  predict:  京B
target:  浙A657BX  ### F ###  predict:  浙5087087
target:  浙A01C32  ### F ###  predict:  浙9B9B9B9B9
target:  鲁CL7205  ### F ###  predict:  浙B59B9595B5B5
target:  苏AH4962  ### F ###  predict:  浙B95B9B595B5959
target:  浙A3AC45  ### F ###  predict:  浙9B9B9B
target:  浙B8V852  ### F ###  predict:  浙B595B5
target:  浙A9P6N9  ### F ###  predict:  浙B9B9B9
target:  浙A66C5Y  ### F ###  predict:  浙B950805050
target:  赣G8750A  ### F ###  predict:  浙9
target:  浙A5Z6M0  ### F ###  predict:  浙9B905085B9
target:  浙A7LD33  ### F ###  predict:  浙B959B5B5

**Comment by luotianhang** [comment]
我用ccpd和自己造的数据集做 重新训练到没你的那么差

**Comment by rawli** [comment]
> 我用ccpd和自己造的数据集做 重新训练到没你的那么差

我用的是
