### ISSUE TITLE
训练过程中，test acc一直为0。有什么训练trick么？

### ISSUE THREAD

**Issue by BaofengZan** [sirius-ai/LPRNet_Pytorch#5]

**Comment by sirius-ai** [comment]
明显模型还没有训练好，确保训练数据形式与repo自带的test数据集一致后 ，按照原始的超参训练一遍看一下结果，如果方便的话，可以私聊提供训练数据集给我分析看。

**Comment by BaofengZan** [comment]
你好，我用的是ccpd数据集中weather子文件夹中的数据，一共9999张数据。用的就是默认的超参数和提供的模型进行微调。我这边继续训练一段时间，如果还不行我在私聊你。谢谢。

**Comment by BaofengZan** [comment]
数据形式和提供的test数据形式一样，图片名为真实label。大小为 94x24

**Comment by sirius-ai** [comment]
ccpd的数据集大部分车牌都是皖A车牌，而我提供的test文件夹下的车牌是包含全国各省市的，因此数据分布不太一致，此外，我用于验证的方法为贪婪验证，只要有一个字符出错就是全错了，因此，出现test acc为0也就不奇怪了！
