### ISSUE TITLE
能识别双行车牌吗？

### ISSUE THREAD

**Issue by xiake007** [sirius-ai/LPRNet_Pytorch#6]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sirius-ai** [comment]
目前仅能识别单行车牌，不过可以在识别输入上做文章以便支持双行车牌识别。

**Comment by Jordan-5i** [comment]
可以提示一下怎样更改输入吗？ @sirius-ai

**Comment by sirius-ai** [comment]
可以上下行分别截取然后再组装成一行送入网络。
