### ISSUE TITLE
能共享一些新能源数据集吗？

### ISSUE THREAD

**Issue by BowieHsu** [sirius-ai/LPRNet_Pytorch#7]
大佬您好，感谢您出色的工作，我们现在想测一下模型在蓝牌和新能源数据上进行训练的效果，您能共享一些新能源数据集出来吗？

**Comment by sirius-ai** [comment]
不好意思，数据集属于私有集。

**Comment by BowieHsu** [comment]
@sirius-ai 明白，还想请教一下哈，您目前这个改动版本的LprNet和intel原版论文里面的有做过比较吗？

**Comment by sirius-ai** [comment]
intel原版论文里面的没有现成的，我也是根据他的论文进行实现的，少了STN等网络而已。
