### ISSUE TITLE
车牌识别商用级别数据集

### ISSUE THREAD

**Issue by daijie1223** [sirius-ai/LPRNet_Pytorch#73]
可提供一手车牌检测和车牌识别商用级别数据集，数据简介见链接：https://www.bilibili.com/video/bv1kU4y1e7Sb

**Comment by wbh604** [comment]
以举报给我校教务处

**Comment by daijie1223** [comment]
> 以举报给我校教务处

可笑,我们自己收集的,还是你的?有本事对比一下啊.
